import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { useEffect } from "react";
import { Navbar } from "@/components/Navbar";
import { Header } from "@/components/Header";
import { Search } from "@/components/Search";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  async function call() {
    const hello = await api.secretData.query();
  }
  useEffect(() => {
    call();
  });
  return (
    <>
      <Head>
        <title>Daily Strive</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#fff] to-[#734ACC]">
        <section className="p-3">
          <Header />
          <h1 className="text-left text-3xl">
            Create your goal for your future
          </h1>
          <Search />
        </section>
        <div className="mt-auto p-2">
          <Navbar />
        </div>
      </main>
    </>
  );
}
