import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Navbar } from "@/components/common/Navbar";
import { Header } from "@/components/common/Header";
import { Search } from "@/components/common/Search";
import { HabitCard } from "@/components/pages/HabitCard";
import { TaskItem } from "@/components/pages/TaskItem";
import { useGetListTask } from "@/features/tasks/api/getListTask";

export default function Home() {
  const {data: listTask} = useGetListTask()

  return (
    <>
      <Head>
        <title>Daily Strive</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />UNSKIN PITKÄ | UNSKI'S LONG
      </Head>
      <main className="relative flex min-h-screen flex-col bg-gradient-to-b from-[#fff] to-[#734ACC]">
        <section className="px-3 pb-1 pt-5">
          <Header />
          <h1 className="mb-5 mt-2 w-2/3 text-left text-2xl">
            Create your goal for your future
          </h1>
          <Search />

          <div className="mt-5">
            <div className="carousel w-full">
              <div id="item1" className="carousel-item w-full">
                <HabitCard />
              </div>
              <div id="item2" className="carousel-item w-full">
                <HabitCard />
              </div>
              <div id="item3" className="carousel-item w-full">
                <HabitCard />
              </div>
              <div id="item4" className="carousel-item w-full">
                <HabitCard />
              </div>
            </div>

            <div className="flex w-full justify-center gap-2 py-2">
              <a href="#item1" className="h-2 w-2 rounded-full bg-white"></a>
              <a href="#item2" className="h-2 w-2 rounded-full bg-white"></a>
              <a href="#item3" className="h-2 w-2 rounded-full bg-white"></a>
              <a href="#item4" className="h-2 w-2 rounded-full bg-white"></a>
            </div>
          </div>
        </section>

        <section
          style={{ height: "calc(58vh)" }}
          className="bg-softTeal h-screen rounded-t-3xl p-4 overflow-hidden"
        >
          <div className="flex justify-between items-center">
            <span className="text-sm font-light">
              You’re almost done, go ahead!
            </span>
            <span className="text-sm font-light">80%</span>
          </div>
          <progress
            className="progress progress-secondary "
            value={80}
            max="100"
          ></progress>

          <div className="mt-3 overflow-y-auto h-full" >
            {listTask && listTask.data.map((item: any) => (
              <TaskItem
                key={item.id}
                streak={0}
                title={item.name}
              />
            ))} 
          </div>
        </section>

        <nav className="absolute bottom-1 mt-auto w-full p-2">
          <Navbar />
        </nav>
      </main>
    </>
  );
}
