import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/router";
import { z } from "zod";
import Head from "next/head";
import { useRegister } from "@/features/auth/api/register";
import CoverImage from '../assets/images/cover.jpg'
import Image from "next/image";


const SignupSchema = z
  .object({
    firstname: z.string({ required_error: "First name is required" }),
    lastname: z.string({ required_error: "Last name is required" }),
    email: z.string({ required_error: "Username is required" }),
    password: z
      .string()
      .min(8, { message: "Password must be at least 8 characters long" }),
    passwordRecheck: z.string().min(8, {
      message: "Re-entered password must be at least 8 characters long",
    }),
  })
  .refine((data) => data.password === data.passwordRecheck, {
    path: ["passwordRecheck"],
    message: "Password does not match",
  });

export type SignUpInput = z.infer<typeof SignupSchema>;

const SignupForm = () => {
  const [apiError, setApiError] = useState("");
  const { mutateAsync: registerUser } = useRegister();
  const router = useRouter();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<SignUpInput>({
    resolver: zodResolver(SignupSchema),
  });

  const onSubmit = async (input: SignUpInput) => {
    if (input.password !== input.passwordRecheck) {
      setApiError("Passwords do not match");
      return;
    }

    const { data } = await registerUser(input);
    if (data.data) {
      router.push("/signin");
    }
  };

  return (
    <>
      <Head>
        <title>Daily Strive</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-5 h-screen w-full p-5">
        <section className="p-6 pt-0 text-center">
          <h1 className="text-4xl font-extrabold leading-none tracking-tight text-gray-900  md:text-5xl lg:text-6xl">
            Sign Up
          </h1>
        <Image className="m-auto w-3/4" src={CoverImage} alt="Cover image" />
          <p className="mb-2 text-sm font-normal text-gray-500 dark:text-gray-400 sm:px-16 lg:text-xl xl:px-48">
          <span className="font-semibold">Daily Strive</span> aims to minimize dropout rates in personal growth
            missions with its user-friendly habit-building app, striving to
            excel in the habit-tracking market.
          </p>
        </section>

        <form
          className="flex-col-center w-full"
          onSubmit={handleSubmit(onSubmit)}
        >
          <input
            type="text"
            className="input input-bordered mb-3 w-full max-w-xs"
            placeholder="Firstname"
            {...register("firstname")}
          />
          {errors.firstname && <p>{errors.firstname.message}</p>}
          <input
            type="text"
            className="input input-bordered mb-3 w-full max-w-xs"
            placeholder="Lastname"
            {...register("lastname")}
          />
          {errors.lastname && <p>{errors.lastname.message}</p>}
          <input
            type="text"
            className="input input-bordered mb-3 w-full max-w-xs"
            placeholder="Username"
            {...register("email")}
          />
          {errors.email && <p>{errors.email.message}</p>}
          <input
            type="password"
            className="input input-bordered mb-3 w-full max-w-xs"
            placeholder="Password"
            {...register("password")}
          />
          {errors.password && <p>{errors.password.message}</p>}
          <input
            type="password"
            className="input input-bordered mb-3 w-full max-w-xs"
            placeholder="Confirm password"
            {...register("passwordRecheck")}
          />
          {errors.passwordRecheck && <p>{errors.passwordRecheck.message}</p>}
          <button className="btn btn-primary btn-wide" type="submit">
            Submit
          </button>
        </form>
        {/* {mutation.isLoading && <p>Loading...</p>} */}
        {apiError && <p>{apiError}</p>}
      </main>
    </>
  );
};

export default SignupForm;
