import { Search } from "@/components/common/Search";
import { TopicCard } from "@/components/pages/TopicCard";
import Book from '../assets/images/book.png'
import Health from '../assets/images/health.png'
import Meditation from '../assets/images/meditation.png'
import Productivity from '../assets/images/productivity.png'
import Sleep from '../assets/images/sleep.png'
import Head from "next/head";
import React from "react";

const TopicPage = () => {
  const data = [
    {
      name: "Staying fit",
      summary: "Be strong and full of energy",
      image: Book
    },
    {
      name: "Learn & explore",
      summary: "Stay hungry for knowledge",
      image: Health
    },
    {
      name: "Better sleep",
      summary: "Quality sleep is key to a healthy lifestyle",
      image: Meditation
    },
    {
      name: "Getting stuff done",
      summary: "Boost your productivity",
      image: Productivity
    },
    {
      name: "Stress relief",
      summary: "Calm down and release tension",
      image: Sleep
    },
    {
      name: "Learn & explore",
      summary: "Stay hungry for knowledge",
      image: Book
    },
  ];

  return (
    <>
      <Head>
        <title>Daily Strive</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="p-3">
        <header className="py-3">
          <h1 className="text-center text-xl font-semibold">Habits</h1>
        </header>
        <Search inputClassName="bg-softGrey" />

        <div className="mt-6">
          {data.map((item) => (
            <TopicCard key={item.name} name={item.name} summary={item.summary} image={item.image}/>
          ))}
        </div>
      </main>
    </>
  );
};

export default TopicPage;
